const path = require("path");
const fs = require("fs");
const {
  withAndroidManifest,
  withDangerousMod,
  AndroidConfig,
} = require("expo/config-plugins");

/**
 * Makes Twilio Voice and expo-notifications share one FCM service on Android.
 *
 * Both libraries ship a FirebaseMessagingService bound to
 * `com.google.firebase.MESSAGING_EVENT`, and Android delivers to exactly one:
 *
 *   expo-notifications  → ExpoFirebaseMessagingService,  priority -1
 *   @twilio/voice-...   → VoiceFirebaseMessagingService, priority  0
 *
 * Twilio's wins on priority, and its onMessageReceived does not forward
 * anything it doesn't recognise — it logs "not a valid Twilio Voice SDK
 * payload" and drops it. So simply registering for Twilio push silently breaks
 * every other notification the app sends: chat, bookings, the lot.
 *
 * The fix is one service that tries Twilio first and hands everything else to
 * Expo. Twilio ships a resource flag for exactly this purpose, so its own
 * service can be switched off without touching its manifest.
 *
 * All three pieces are generated here rather than edited into the android/
 * directory by hand, so a clean prebuild reproduces them.
 */

const SERVICE_CLASS = "BikeOpsMessagingService";

/** Twilio's own opt-out for the service it registers. */
function withTwilioServiceDisabled(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const valuesDir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app/src/main/res/values"
      );
      fs.mkdirSync(valuesDir, { recursive: true });
      fs.writeFileSync(
        path.join(valuesDir, "twilio_voice_overrides.xml"),
        `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withTwilioVoiceAndroid.js — do not edit by hand.
     Turns off Twilio's own FirebaseMessagingService so ${SERVICE_CLASS}
     can be the single service for both libraries. -->
<resources>
    <bool name="twiliovoicereactnative_firebasemessagingservice_enabled">false</bool>
</resources>
`,
        "utf8"
      );
      return cfg;
    },
  ]);
}

/** The merged service: Twilio first, Expo for everything else. */
function withMergedMessagingService(config) {
  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const pkg = AndroidConfig.Package.getPackage(cfg);
      if (!pkg) throw new Error("withTwilioVoiceAndroid: android.package is not set");

      const dir = path.join(
        cfg.modRequest.platformProjectRoot,
        "app/src/main/java",
        ...pkg.split(".")
      );
      fs.mkdirSync(dir, { recursive: true });

      fs.writeFileSync(
        path.join(dir, `${SERVICE_CLASS}.kt`),
        `package ${pkg}

// Generated by plugins/withTwilioVoiceAndroid.js — do not edit by hand.

import com.google.firebase.messaging.RemoteMessage
import com.twilio.voice.Voice
import com.twiliovoicereactnative.CallMessageListenerProxy
import com.twiliovoicereactnative.VoiceFirebaseMessagingService
import expo.modules.notifications.service.ExpoFirebaseMessagingService

/**
 * The app's single FirebaseMessagingService.
 *
 * Android delivers an FCM message to one service, and both Twilio Voice and
 * expo-notifications want to be it. Twilio's own service is switched off (see
 * twilio_voice_overrides.xml) and this stands in for both: Voice.handleMessage
 * returns false for anything that is not a voice payload, which is the signal
 * to pass it to Expo instead.
 *
 * Getting this wrong is not subtle — whichever library loses stops receiving
 * anything at all.
 */
class ${SERVICE_CLASS} : ExpoFirebaseMessagingService() {
  override fun onMessageReceived(remoteMessage: RemoteMessage) {
    val data = remoteMessage.data
    val handledByTwilio = data.isNotEmpty() && runCatching {
      Voice.handleMessage(
        this,
        data,
        VoiceFirebaseMessagingService.MessageHandler(),
        CallMessageListenerProxy()
      )
    }.getOrDefault(false)

    // Not a call: it is a chat message, a booking, a reminder. Expo's delegate
    // is what turns those into notifications.
    if (!handledByTwilio) {
      super.onMessageReceived(remoteMessage)
    }
  }

  // Expo owns token registration; Twilio is handed its token by the JS layer
  // when voice.register() is called, so it needs nothing here.
  override fun onNewToken(token: String) {
    super.onNewToken(token)
  }
}
`,
        "utf8"
      );
      return cfg;
    },
  ]);
}

/** Registers the merged service, at the default priority Twilio's vacated. */
function withMergedServiceInManifest(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.service = app.service ?? [];

    const name = `.${SERVICE_CLASS}`;
    if (app.service.some((s) => s.$?.["android:name"] === name)) return cfg;

    app.service.push({
      $: {
        "android:name": name,
        "android:exported": "false",
        // stopWithTask=false matches Twilio's own declaration: a call has to be
        // able to arrive after the task is swiped away.
        "android:stopWithTask": "false",
      },
      "intent-filter": [
        { action: [{ $: { "android:name": "com.google.firebase.MESSAGING_EVENT" } }] },
      ],
    });

    return cfg;
  });
}

module.exports = (config) => {
  config = withTwilioServiceDisabled(config);
  config = withMergedMessagingService(config);
  config = withMergedServiceInManifest(config);
  return config;
};
